### ISSUE TITLE
[feat] Allow to use stdin to pipe commands

### ISSUE THREAD

**Issue by dj4ngo** [gr0und-s3ct0r/niet#12]
Allow to read input directly from stdin instead of a file

A good comportment could be : 
If there is something in stdin and no input file, read file from stdin. 
If there an stdin and an input file is specified, read path from stdin.
If there is nothing on stdin, continue as usual by reading file and pattern from file and argument.

This will certainly imply to change a bit the way we are parsing positional argument. It becomes optional and should return an error when no argument is given and stdin is empty.

**Comment by 4383** [comment]
It seem to be an interesting feature proposal.
Can you provide more examples of the expected behavior?
